# UP-Fall dataset config.yaml

dataset_processor_params:
  cam_fps: 30
  sequence_length: 3
  overlapping_frame_window : 75
  dataset_path : "~/Downloads/UPFallDataset"
  out_path : "~/Fall_detection_dataset/UP-Fall dataset/out/fall-up.json"